# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    environment:
      LOFI_APP_HOST: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
      LOFI_APP_PORT: ${LOFI_APP_PORT:-8010}
      LOFI_API_HOST: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
      LOFI_API_PORT: ${LOFI_API_PORT:-8020}
    volumes:
      - ./Lofi.Nginx/development:/etc/nginx/templates/
      - ${MUSIC_DIRECTORY:-~/music}:/var/www/lofi/media
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "lofiuser"
      POSTGRES_PASSWORD: "lofiuser"
      POSTGRES_DB: "lofi"
    volumes:
      - "${PG_DATA_DIR:-~/pg}:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8030:8080
    depends_on:
      - db
  monerod:
    image: xmrto/monero:v0.17.2.0
    command: --testnet --data-dir /monero
    volumes:
      - "${MONEROD_DATA_DIR:-~/.bitmonero}:/monero"
    ports:
      - 28080:28080
      - 28081:28081
    restart: unless-stopped
  monero-wallet-rpc:
    image: xmrto/monero:v0.17.2.0
    command: monero-wallet-rpc --testnet --disable-rpc-login --wallet-dir /monero/wallets
    volumes:
      - "${MONEROD_DATA_DIR:-~/.bitmonero}:/monero"
    environment:
      - DAEMON_HOST=monerod
      - DAEMON_PORT=28081
      - RPC_BIND_PORT=28083
    ports:
      - 28083:28083
    restart: unless-stopped
    depends_on:
      - monerod

