# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    image: lofi/api
    build:
      context: Lofi.API
    ports:
      - 8010:80
    volumes:
      - "${MUSIC_DIRECTORY:-~/music}:/music"
    depends_on:
      - db
  nginx:
    image: lofi/nginx
    build:
      context: Lofi.Nginx
    ports:
      - 80:80
    volumes:
      - "${MUSIC_DIRECTORY:-~/music}:/var/www/lofi/media"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "lofiuser"
      POSTGRES_PASSWORD: "lofiuser"
      POSTGRES_DB: "lofi"
    volumes:
      - "${PG_DATA_DIR:-pgdata}:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8030:8080
  monerod:
    image: xmrto/monero:v0.17.2.0
    command: --testnet --data-dir /monero
    volumes:
      - "${MONEROD_DATA_DIR:-~/.bitmonero}:/monero"
    ports:
      - 28080:28080
      - 28081:28081
    restart: unless-stopped
  monero-wallet-rpc:
    image: xmrto/monero:v0.17.2.0
    command: monero-wallet-rpc --testnet --disable-rpc-login --wallet-dir /monero/wallets
    volumes:
      - "${MONEROD_DATA_DIR:-~/.bitmonero}:/monero"
    environment:
      - DAEMON_HOST=monerod
      - DAEMON_PORT=28080
      - RPC_BIND_PORT=28083
    ports:
      - 28083:28083
    restart: unless-stopped
    depends_on:
      - monerod