FROM nginx:alpine
EXPOSE 80
VOLUME [ "/etc/nginx/nginx.conf", "/var/www/lofi/media" ]


RUN apk add --no-cache inotify-tools

WORKDIR /home/nginx
COPY entrypoint.dev.sh .
ENTRYPOINT [ "./entrypoint.dev.sh" ]