FROM mcr.microsoft.com/dotnet/sdk:5.0
VOLUME ["/src"]
WORKDIR /src
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80

COPY dotnet-tools.json .
COPY Lofi.API.csproj .
RUN dotnet tool restore && dotnet restore

CMD ["dotnet", "watch", "run"]
